#!/bin/sh

############################################################################
REPOSITORY_PATH=$1
ENVIRONMENT=$2

############################################################################
CURRENT_FOLDER=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $CURRENT_FOLDER/../config/config

############################################################################
REPOSITORY_NAME=$(echo "$REPOSITORY_PATH" | tr \/ \:)
CONTAINER_NAME=$(echo "$REPOSITORY_NAME" | tr \: 0)
WORK_FOLDER=$WORK_BASE_FOLDER/$REPOSITORY_PATH
WORK_DOCKER_FOLDER=$WORK_FOLDER/$DOCKER_FOLDER

############################################################################
rm -rf $WORK_FOLDER
ssh-keyscan github.com >> ~/.ssh/known_hosts
# optimize, if folder exists, only pull
ssh-agent $(ssh-add $CURRENT_FOLDER/../config/id_rsa; git clone --verbose --progress --depth=1 git@$REPOSITORY_BASEURL:$REPOSITORY_PATH $WORK_FOLDER)

############################################################################
cd $WORK_DOCKER_FOLDER
docker-machine start $DOCKER_MACHINE_NAME
eval "$(docker-machine env $DOCKER_MACHINE_NAME)"
docker build -t="$REPOSITORY_NAME" .
docker run --rm --name "$CONTAINER_NAME" -e TSDC_ENVIRONMENT=$ENVIRONMENT -ti -p 8080:8080 -p 5601:5601 "$REPOSITORY_NAME"